apiVersion: apps/v1
kind: Deployment
metadata:
  name: united-atomic-bank-api-deployment
  labels:
    app: united-atomic-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: united-atomic-bank-api
  template:
    metadata:
      labels:
        app: united-atomic-bank-api
    spec:
      containers:
      - name: united-atomic-bank-api
        image: 563349842391.dkr.ecr.sa-east-1.amazonaws.com/united_atomic_bank:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080