global:
  scrape_interval: 5s

scrape_configs:
- job_name: prometheus
  scheme: http
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:9090
- job_name: node-exporter
  scheme: http
  metrics_path: /metrics
  static_configs:
  - targets: 
    - node-exporter:9100
- job_name: cAdvisor
  scheme: http
  metrics_path: /metrics
  static_configs:
  - targets: 
    - cadvisor:8080
- job_name: uab
  scheme: http
  metrics_path: /metrics
  follow_redirects: true
  static_configs:
  - targets: 
    - api:80