// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: loan_transfer.sql

package db

import (
	"context"
	"time"
)

const createLoanTransfer = `-- name: CreateLoanTransfer :one
INSERT INTO loan_transfers (
  account_id,
  loan_amount,
  interest_rate,
  status,
  end_date
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, account_id, loan_amount, interest_rate, status, start_date, end_date
`

type CreateLoanTransferParams struct {
	AccountID    int64     `json:"account_id"`
	LoanAmount   int64     `json:"loan_amount"`
	InterestRate int64     `json:"interest_rate"`
	Status       string    `json:"status"`
	EndDate      time.Time `json:"end_date"`
}

func (q *Queries) CreateLoanTransfer(ctx context.Context, arg CreateLoanTransferParams) (LoanTransfer, error) {
	row := q.db.QueryRowContext(ctx, createLoanTransfer,
		arg.AccountID,
		arg.LoanAmount,
		arg.InterestRate,
		arg.Status,
		arg.EndDate,
	)
	var i LoanTransfer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LoanAmount,
		&i.InterestRate,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getLoanTransfer = `-- name: GetLoanTransfer :one
SELECT id, account_id, loan_amount, interest_rate, status, start_date, end_date FROM loan_transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLoanTransfer(ctx context.Context, id int64) (LoanTransfer, error) {
	row := q.db.QueryRowContext(ctx, getLoanTransfer, id)
	var i LoanTransfer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LoanAmount,
		&i.InterestRate,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
