// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transfer.sql

package db

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  from_account_id,
  from_account_owner,
  to_account_id,
  to_account_owner,
  amount
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, from_account_id, from_account_owner, to_account_id, to_account_owner, amount, created_at
`

type CreateTransferParams struct {
	FromAccountID    int64  `json:"from_account_id"`
	FromAccountOwner string `json:"from_account_owner"`
	ToAccountID      int64  `json:"to_account_id"`
	ToAccountOwner   string `json:"to_account_owner"`
	Amount           int64  `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer,
		arg.FromAccountID,
		arg.FromAccountOwner,
		arg.ToAccountID,
		arg.ToAccountOwner,
		arg.Amount,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.FromAccountOwner,
		&i.ToAccountID,
		&i.ToAccountOwner,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, from_account_id, from_account_owner, to_account_id, to_account_owner, amount, created_at FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.FromAccountOwner,
		&i.ToAccountID,
		&i.ToAccountOwner,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, from_account_id, from_account_owner, to_account_id, to_account_owner, amount, created_at FROM transfers
WHERE 
    from_account_owner = $1 OR
    to_account_owner = $2
ORDER BY id
LIMIT $3
OFFSET $4
`

type ListTransfersParams struct {
	FromAccountOwner string `json:"from_account_owner"`
	ToAccountOwner   string `json:"to_account_owner"`
	Limit            int32  `json:"limit"`
	Offset           int32  `json:"offset"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers,
		arg.FromAccountOwner,
		arg.ToAccountOwner,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.FromAccountOwner,
			&i.ToAccountID,
			&i.ToAccountOwner,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
