name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Create app.env file
      run: |
        touch app.env

        echo DB_DRIVER=postgres >> app.env
        echo DB_SOURCE=postgresql://root:secret@localhost:5432/bank?sslmode=disable >> app.env
        echo HTTP_SERVER_ADDRESS=0.0.0.0:8080 >> app.env
        echo TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012 >> app.env
        echo ACCESS_TOKEN_DURATION=15m >> app.env

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
