name: Build & Publish Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create app.env file
      run: |
        cat > app.env << EOF
          DB_DRIVER=postgres
          DB_SOURCE=postgresql://root:secret@localhost:5432/bank?sslmode=disable
          HTTP_SERVER_ADDRESS=0.0.0.0:8080

          TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
          ACCESS_TOKEN_DURATION=15m
        EOF

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: united_atomic_bank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
